const LODING_REQUEST = 'LODING_REQUEST';

const FETCH_FIRST_DATA_SUCCESS = 'FETCH_FIRST_DATA_SUCCESS';
const FETCH_FIRST_DATA_ERROR = 'FETCH_FIRST_DATA_ERROR';


const FETCH_SECOND_DATA_SUCCESS = 'FETCH_SECOND_DATA_SUCCESS'; 
const FETCH_SECOND_DATA_ERROR = 'FETCH_SECOND_DATA_ERROR';



export {
    LODING_REQUEST,
    FETCH_FIRST_DATA_SUCCESS,
    FETCH_FIRST_DATA_ERROR,
    FETCH_SECOND_DATA_SUCCESS,
    FETCH_SECOND_DATA_ERROR
}